name = "FusionRings"
uuid = "2d8f65af-6f64-4f8e-9a4a-6a8c0dfc3f5b"
version = "0.2.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"

[weakdeps]
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"

[extensions]
FusionRingsOSCARExt = "Oscar"
FusionRingsBSONExt = "BSON"

[compat]
julia = "1.9, 1.10, 1.11"
JSON3 = "1"
Combinatorics = "1"
