name = "FusionRings"
uuid = "609e252f-52eb-439d-abe9-2fbe746db898"
authors = ["Gert Vercleyen gert.vercleyen@protonmail.com"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
Combinatorics = "1.0.3"
Oscar = "1.4.1"
Revise = "3.8.0"
