name = "FusionRings"
uuid = "2d8f65af-6f64-4f8e-9a4a-6a8c0dfc3f5b"
authors = ["FusionRings Devs <devnull@example.com>"]
version = "0.1.0"

[deps]


LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
[extras]
Test = "8dfed614-e22c-5e08-85e1-65c572dbe5c6"

[targets]
test = ["Test"]
